---
title: "Research"
output: html_document
---
-------------------
### **Publications**
Wang, T., Cooper Borkenhagen, M., Barker, M., & Seidenberg, M.S. (2022) Meanings within meanings: Skilled readers activate irrelevant meanings of radicals and phonetics in Chinese. _Reading and Writing_.

Lewis, M., Cooper Borkenhagen, M., Converse, E., Lupyan, G., & Seidenberg, M. S. (2022). What might books be teaching young children about gender? _Psychological Science, 33_(1), 1 - 15.

Seidenberg, M. S., Borkenhagen, M. C., & Kearns, D. M. (2020). Lost in translation? Challenges in connecting reading science and educational practice. _Reading Research Quarterly, 55_(S1), S119-S130.

Seidenberg, M. S., & Borkenhagen, M. C. (2020). Reading science and educational practice: Some tenets for teachers. _The Reading League Journal, 1_(1), 7-11.
<!-- [`[pdf]`](./data/seidenberg_etal_2020_rlj.pdf) -->

Cox, C., Borkenhagen, M. C., & Seidenberg, M. S. (2019) Efficiency of learning in experience-limited domains: Generalization beyond the WUG test. In A.K. Goel, C.M Seifert, & C. Freksa (Eds.), _Proceedings of the 41st Annual Conference of the Cognitive Science Society_ (pp. 1566-1571). Montreal, QB. Cognitive Science Society. [`[pdf]`](https://cogsci.mindmodeling.org/2019/papers/0281/0281.pdf)

<br>

### **Under review**
Sen, A., Cox, C. R., Borkenhagen, M. C., Seidenberg, M. S., & Zhu, J. (2020, July 2). Learning to read through machine teaching. [`[preprint]`](https://arxiv.org/pdf/2006.16470.pdf)

Cooper Borkenhagen, M., Schilling, L., & Seidenberg, M. S. (in prep). Special words: The contents of popular sight word inventories and their instructional framing.

Cooper Borkenhagen, M., Lewis., M., Borman, M., Converse, E., & Seidenberg, M. S. (in
prep). The Wisconsin Childrens' Book Corpus: A corpus of popular American child-directed texts.
